// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: wallet.sql

package model

import (
	"context"
)

const addNewWallet = `-- name: AddNewWallet :one
INSERT INTO wallet ( metamask_wallet_id, follow_wallet, id_user, id_chain, last_block_number,  wallet_name)
VALUES ( $1, true, $2, 1, 0, '') RETURNING wallet_id, metamask_wallet_id, follow_wallet, id_user, id_chain, last_block_number, created_at, modified, deleted, wallet_name
`

type AddNewWalletParams struct {
	MetamaskWalletID string `json:"metamask_wallet_id"`
	IDUser           int32  `json:"id_user"`
}

func (q *Queries) AddNewWallet(ctx context.Context, arg AddNewWalletParams) (Wallet, error) {
	row := q.db.QueryRowContext(ctx, addNewWallet, arg.MetamaskWalletID, arg.IDUser)
	var i Wallet
	err := row.Scan(
		&i.WalletID,
		&i.MetamaskWalletID,
		&i.FollowWallet,
		&i.IDUser,
		&i.IDChain,
		&i.LastBlockNumber,
		&i.CreatedAt,
		&i.Modified,
		&i.Deleted,
		&i.WalletName,
	)
	return i, err
}
